In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("credit_card_fraud_2026.csv")
print(df.head())

   transaction_id  amount_usd merchant_category   card_type  \
0               1       42.86       Restaurants        Visa
1               2        4.75     Online Retail  Mastercard
2               3       77.18         Groceries  Mastercard
3               4        1.69         Streaming        Visa
4               5      261.68            Travel        Visa

         auth_method channel    device_type  is_foreign_transaction  \
0                OTP  Online  Android Phone                   False
1          3D Secure  Online  Android Phone                   False
2          3D Secure  Online            Mac                   False
3  No Authentication     POS  Android Phone                   False
4          3D Secure  In-App         iPhone                   False

   hours_since_last_txn  txn_count_last_24h  ...  ip_country_mismatch  \
0                 13.54                   2  ...                False
1                  0.71                   2  ...                False
2                  0.35                   5  ...                False
3                  3.42                   6  ...                False
4                  2.43                   2  ...                False

   billing_shipping_mismatch  cvv_retry_count  velocity_score  \
0                      False                0             0.1
1                      False                0            25.8
2                       True                0            42.3
3                      False                0            28.9
4                      False                0             3.9

   time_of_day_hour  day_of_week  is_ai_generated_scam_attempt  \
0                18            3                         False
1                12            4                         False
2                 5            0                         False
3                22            6                         False
4                 2            4                         False

   merchant_risk_score  prior_disputes  is_fraud
0                 42.3               0         0
1                 28.3               0         0
2                 24.7               1         0
3                 56.2               1         0
4                 32.7               0         0

[5 rows x 26 columns]

In [4]:
import pandas as pd
import numpy as np
df=pd.read_csv("credit_card_fraud_2026.csv")
# Total amount used by card
print("Sum of amount by card_type:")
display(df.groupby("card_type")["amount_usd"].sum())

# Average price per card
print("\nMean amount by card type:")
display(df.groupby("card_type")["amount_usd"].mean())

# Multiple aggregations at once with agg()
print("\nMultiple aggregations with agg():")
display(df.groupby("card_type").agg(
    total_qty=("amount_usd", "sum"),
    avg_price=("hours_since_last_txn", "mean"),
    order_count=("transaction_id", "count")
))

Sum of amount by card_type:

card_type
Amex           292478.59
Discover       134472.04
Mastercard     891392.24
RuPay          237133.21
Visa          1093015.86
Name: amount_usd, dtype: float64

Mean amount by card type:

card_type
Amex          136.992314
Discover      131.448719
Mastercard    134.468583
RuPay         132.034081
Visa          129.858128
Name: amount_usd, dtype: float64

Multiple aggregations with agg():

             total_qty  avg_price  order_count
card_type
Amex         292478.59   8.899808         2135
Discover     134472.04   8.441838         1023
Mastercard   891392.24   9.051842         6629
RuPay        237133.21   9.120457         1796
Visa        1093015.86   8.909880         8417

In [6]:
pivot = pd.pivot_table(
    df,
    values="amount_usd",
    index="card_type",
    columns="device_type",
    aggfunc="sum",
    fill_value=0
)
pivot

device_type,ATM Machine,Android Phone,Mac,POS Terminal,Smart Watch,Tablet,Windows PC,iPhone
card_type,,,,,,,,
Amex,15207.29,89823.94,21871.59,40546.48,11467.98,12733.53,38884.32,61943.46
Discover,5877.83,38849.26,11613.46,21287.46,4943.85,7344.75,16553.08,28002.35
Mastercard,53378.23,233467.70,54495.64,143734.62,43118.94,49452.62,124395.38,189349.11
RuPay,13540.72,62876.88,18591.59,37023.07,9678.80,14084.43,29113.19,52224.53
Visa,62989.09,296860.28,68417.12,163305.84,52477.69,63766.14,147665.27,237534.43

In [8]:
print("Missing values per column:")
display(df.isnull().sum())

print("\nRows with any missing values:")
display(df[df.isnull().any(axis=1)])

print("\nDropping rows with missing values (dropna):")
display(df.dropna())

print("\nFilling missing Quantity with the column mean (fillna):")
df_filled = df.copy()
df_filled["amount_usd"] = df_filled["amount_usd"].fillna(df_filled["amount_usd"].mean())
display(df_filled)

Missing values per column:

transaction_id                  0
amount_usd                      0
merchant_category               0
card_type                       0
auth_method                     0
channel                         0
device_type                     0
is_foreign_transaction          0
hours_since_last_txn            0
txn_count_last_24h              0
distance_from_home_km           0
card_age_months                 0
customer_age                    0
account_balance_usd             0
is_new_merchant                 0
used_vpn                        0
ip_country_mismatch             0
billing_shipping_mismatch       0
cvv_retry_count                 0
velocity_score                  0
time_of_day_hour                0
day_of_week                     0
is_ai_generated_scam_attempt    0
merchant_risk_score             0
prior_disputes                  0
is_fraud                        0
dtype: int64

Rows with any missing values:

Empty DataFrame
Columns: [transaction_id, amount_usd, merchant_category, card_type, auth_method, channel, device_type, is_foreign_transaction, hours_since_last_txn, txn_count_last_24h, distance_from_home_km, card_age_months, customer_age, account_balance_usd, is_new_merchant, used_vpn, ip_country_mismatch, billing_shipping_mismatch, cvv_retry_count, velocity_score, time_of_day_hour, day_of_week, is_ai_generated_scam_attempt, merchant_risk_score, prior_disputes, is_fraud]
Index: []

[0 rows x 26 columns]

Dropping rows with missing values (dropna):

,transaction_id,amount_usd,merchant_category,card_type,auth_method,channel,device_type,is_foreign_transaction,hours_since_last_txn,txn_count_last_24h,...,ip_country_mismatch,billing_shipping_mismatch,cvv_retry_count,velocity_score,time_of_day_hour,day_of_week,is_ai_generated_scam_attempt,merchant_risk_score,prior_disputes,is_fraud
0,1,42.86,Restaurants,Visa,OTP,Online,Android Phone,False,13.54,2,...,False,False,0,0.1,18,3,False,42.3,0,0
1,2,4.75,Online Retail,Mastercard,3D Secure,Online,Android Phone,False,0.71,2,...,False,False,0,25.8,12,4,False,28.3,0,0
2,3,77.18,Groceries,Mastercard,3D Secure,Online,Mac,False,0.35,5,...,False,True,0,42.3,5,0,False,24.7,1,0
3,4,1.69,Streaming,Visa,No Authentication,POS,Android Phone,False,3.42,6,...,False,False,0,28.9,22,6,False,56.2,1,0
4,5,261.68,Travel,Visa,3D Secure,In-App,iPhone,False,2.43,2,...,False,False,0,3.9,2,4,False,32.7,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,41.40,Healthcare,Mastercard,OTP,POS,Android Phone,False,8.82,2,...,False,False,0,17.3,2,3,False,29.6,1,0
19996,19997,47.92,Online Retail,Visa,OTP,POS,Android Phone,False,45.81,1,...,False,False,0,9.0,4,0,False,29.2,1,0
19997,19998,10.25,Restaurants,Visa,3D Secure,In-App,Tablet,False,20.67,0,...,False,False,1,1.0,19,5,False,22.9,0,0
19998,19999,31.34,Travel,Visa,3D Secure,Online,Android Phone,False,22.94,2,...,False,False,0,8.8,2,1,False,27.9,0,0
19999,20000,47.70,Online Retail,Mastercard,Biometric,Online,iPhone,False,1.20,6,...,False,False,0,41.9,0,6,False,14.4,0,0

Filling missing Quantity with the column mean (fillna):

,transaction_id,amount_usd,merchant_category,card_type,auth_method,channel,device_type,is_foreign_transaction,hours_since_last_txn,txn_count_last_24h,...,ip_country_mismatch,billing_shipping_mismatch,cvv_retry_count,velocity_score,time_of_day_hour,day_of_week,is_ai_generated_scam_attempt,merchant_risk_score,prior_disputes,is_fraud
0,1,42.86,Restaurants,Visa,OTP,Online,Android Phone,False,13.54,2,...,False,False,0,0.1,18,3,False,42.3,0,0
1,2,4.75,Online Retail,Mastercard,3D Secure,Online,Android Phone,False,0.71,2,...,False,False,0,25.8,12,4,False,28.3,0,0
2,3,77.18,Groceries,Mastercard,3D Secure,Online,Mac,False,0.35,5,...,False,True,0,42.3,5,0,False,24.7,1,0
3,4,1.69,Streaming,Visa,No Authentication,POS,Android Phone,False,3.42,6,...,False,False,0,28.9,22,6,False,56.2,1,0
4,5,261.68,Travel,Visa,3D Secure,In-App,iPhone,False,2.43,2,...,False,False,0,3.9,2,4,False,32.7,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,41.40,Healthcare,Mastercard,OTP,POS,Android Phone,False,8.82,2,...,False,False,0,17.3,2,3,False,29.6,1,0
19996,19997,47.92,Online Retail,Visa,OTP,POS,Android Phone,False,45.81,1,...,False,False,0,9.0,4,0,False,29.2,1,0
19997,19998,10.25,Restaurants,Visa,3D Secure,In-App,Tablet,False,20.67,0,...,False,False,1,1.0,19,5,False,22.9,0,0
19998,19999,31.34,Travel,Visa,3D Secure,Online,Android Phone,False,22.94,2,...,False,False,0,8.8,2,1,False,27.9,0,0
19999,20000,47.70,Online Retail,Mastercard,Biometric,Online,iPhone,False,1.20,6,...,False,False,0,41.9,0,6,False,14.4,0,0

In [ ]:
df_t = df_filled.copy()

# apply(): create a new column using a custom function
df_t["Total"] = df_t.apply(lambda row: row["amount_usd"] * row["hours_since_last_txn"], axis=1)

# map(): map values in a column to new values
card_ttype = {"Visa": "Visa", "Mastercard": "Mastercard", "Discover": "Discover", "Amex": "Amex"}
df_t["card_type"] = df_t["card_type"].map(card_ttype)

# astype(): change a column's data type
df_t["amount_usd"] = df_t["amount_usd"].astype(int)

# rename(): rename columns
df_t = df_t.rename(columns={"Total": "TotalRevenue"})

# sort_values(): sort rows by a column
df_t = df_t.sort_values(by="transaction_id", ascending=False)

df_t

,transaction_id,amount_usd,merchant_category,card_type,auth_method,channel,device_type,is_foreign_transaction,hours_since_last_txn,txn_count_last_24h,...,cvv_retry_count,velocity_score,time_of_day_hour,day_of_week,is_ai_generated_scam_attempt,merchant_risk_score,prior_disputes,is_fraud,TotalRevenue,RegionCode
13959,13960,3661,Electronics,Visa,Biometric,POS,Windows PC,False,72.51,7,...,0,37.2,6,4,False,64.4,0,0,265460.5602,Visa
8509,8510,5435,Travel,Mastercard,3D Secure,Online,iPhone,False,17.33,3,...,0,19.9,7,4,False,24.2,0,0,94196.0019,Mastercard
5713,5714,2018,Travel,Visa,PIN,Online,iPhone,False,39.01,5,...,0,26.4,3,4,False,20.0,0,0,78760.0197,Visa
11313,11314,2244,Electronics,Amex,OTP,Contactless,Android Phone,False,29.32,1,...,0,3.8,20,0,False,59.3,0,0,65813.4312,Amex
3997,3998,3039,Travel,Mastercard,PIN,Online,iPhone,False,21.27,6,...,0,45.0,22,5,False,28.1,1,0,64648.6761,Mastercard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3863,3864,7,Utilities,Visa,No Authentication,ATM,POS Terminal,False,0.01,5,...,1,62.2,15,4,False,20.7,0,0,0.0789,Visa
18135,18136,7,Streaming,Visa,3D Secure,Online,iPhone,False,0.01,3,...,0,46.4,11,3,False,30.2,0,0,0.0780,Visa
3726,3727,6,Online Retail,Visa,OTP,POS,Windows PC,False,0.01,3,...,0,56.9,13,5,False,27.9,1,0,0.0695,Visa
9093,9094,2,Streaming,Amex,PIN,Online,POS Terminal,False,0.02,6,...,1,71.6,4,0,False,31.0,0,0,0.0406,Amex
15319,15320,2,Streaming,Mastercard,3D Secure,POS,Windows PC,False,0.01,4,...,0,50.2,15,5,False,18.9,1,0,0.0293,Mastercard